from enum import Enum

class RoleEnum(str, Enum):
    CLIENTE = "CLIENTE"
    EMPLEADO_CAJERO = "EMPLEADO-CAJERO"
    EMPLEADO_OTRO = "EMPLEADO-OTRO"
    ADMIN_MULTIPLEX = "ADMIN-MULTIPLEX"
    ADMIN_GENERAL = "ADMIN-GENERAL"