"""Modelos ORM para Cinepacho."""

from .boleta import Boleta
from .cliente import Cliente
from .comida import Comida
from .configuracion import Configuracion
from .contrato import Contrato
from .detalleFactura import DetalleFactura
from .empleado import Empleado
from .evaluacion import Evaluacion
from .factura import Factura
from .funcion import Funcion
from .multiplex import Multiplex
from .pago import Pago
from .pelicula import Pelicula
from .permiso import Permiso
from .persona import Persona
from .rol_permiso import rol_permiso
from .rol import Rol
from .sala import Sala
from .servicio import Servicio
from .silla import Silla
from .tipoSilla import TipoSilla
from .usuario import Usuario