"""Alembic migration script template."""
"""update evaluaciones

Revision ID: 11629e0d629c
Revises: 61697b798f40
Create Date: 2026-05-24 00:27:47.161194
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '11629e0d629c'
down_revision = '61697b798f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluaciones', sa.Column('funcion_id', sa.Integer(), nullable=True))
    op.add_column('evaluaciones', sa.Column('factura_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_cliente_funcion_pelicula', 'evaluaciones', ['cliente_id', 'funcion_id', 'pelicula_id'])
    op.create_foreign_key(None, 'evaluaciones', 'facturas', ['factura_id'], ['id'])
    op.create_foreign_key(None, 'evaluaciones', 'funciones', ['funcion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluaciones', type_='foreignkey')
    op.drop_constraint(None, 'evaluaciones', type_='foreignkey')
    op.drop_constraint('uq_cliente_funcion_pelicula', 'evaluaciones', type_='unique')
    op.drop_column('evaluaciones', 'factura_id')
    op.drop_column('evaluaciones', 'funcion_id')
    # ### end Alembic commands ###