"""Alembic migration script template."""
"""add unique to comidas nombre

Revision ID: 1dd537df7aec
Revises: 8f315aacea62
Create Date: 2026-05-23 09:04:04.220684
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1dd537df7aec'
down_revision = '8f315aacea62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'comidas', ['nombre'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comidas', type_='unique')
    # ### end Alembic commands ###