"""Alembic migration script template."""
"""add unique to factura codigoTransaccion

Revision ID: 38c65143296b
Revises: 1dd537df7aec
Create Date: 2026-05-23 09:12:18.177619
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '38c65143296b'
down_revision = '1dd537df7aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'facturas', ['codigoTransaccion'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'facturas', type_='unique')
    # ### end Alembic commands ###