"""Alembic migration script template."""
"""unique evaluacion servicio

Revision ID: 3db350fc2764
Revises: 48b5fdfb9a65
Create Date: 2026-05-24 19:45:54.127217
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3db350fc2764'
down_revision = '48b5fdfb9a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cliente_factura_servicio', 'evaluaciones', ['cliente_id', 'factura_id', 'servicio_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cliente_factura_servicio', 'evaluaciones', type_='unique')
    # ### end Alembic commands ###