"""Alembic migration script template."""
"""Add login attempts and blocking fields to Cliente

Revision ID: 458894e040b9
Revises: ddf41aba2d53
Create Date: 2026-05-05 01:31:32.750623
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '458894e040b9'
down_revision = 'ddf41aba2d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('intentos_fallidos', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True))
    op.drop_constraint('uq_sala_numero_multiplex', 'salas', type_='unique')
    op.create_unique_constraint('uq_sala_numero_multiplex', 'salas', ['numero', 'multiplexId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sala_numero_multiplex', 'salas', type_='unique')
    op.create_unique_constraint(op.f('salas_numero_key'), 'salas', ['numero'], postgresql_nulls_not_distinct=False)
    op.drop_column('clientes', 'bloqueado_hasta')
    op.drop_column('clientes', 'intentos_fallidos')
    # ### end Alembic commands ###