"""Alembic migration script template."""
"""add unique constraints

Revision ID: 5c80212b94fc
Revises: 38c65143296b
Create Date: 2026-05-23 09:16:56.549576
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5c80212b94fc'
down_revision = '38c65143296b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sala_fecha_inicio', 'funciones', ['salaId', 'fechaHora'])
    op.create_unique_constraint('uq_silla_sala', 'sillas', ['fila', 'columna', 'salaId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_silla_sala', 'sillas', type_='unique')
    op.drop_constraint('uq_sala_fecha_inicio', 'funciones', type_='unique')
    # ### end Alembic commands ###