"""Alembic migration script template."""
"""add activa to comida

Revision ID: 61697b798f40
Revises: 5c80212b94fc
Create Date: 2026-05-23 10:29:34.885348
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '61697b798f40'
down_revision = '5c80212b94fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comidas', sa.Column('estaActiva', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comidas', 'estaActiva')
    # ### end Alembic commands ###