"""Alembic migration script template."""
"""Add codigo_empleado to Empleado

Revision ID: 62d1636e4e5d
Revises: fa5a32602dd1
Create Date: 2026-05-05 02:22:50.405972
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '62d1636e4e5d'
down_revision = 'fa5a32602dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('codigo_empleado', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'empleados', ['codigo_empleado'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empleados', type_='unique')
    op.drop_column('empleados', 'codigo_empleado')
    # ### end Alembic commands ###