"""Alembic migration script template."""
"""remove unique constraint boleta

Revision ID: 6303acc11909
Revises: ea7b6c2bfdfd
Create Date: 2026-05-24 18:47:44.448960
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6303acc11909'
down_revision = 'ea7b6c2bfdfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_boleta_funcion_silla'), 'boletas', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_boleta_funcion_silla'), 'boletas', ['funcionId', 'sillaId'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###