"""Alembic migration script template."""
"""init

Revision ID: 700758466f79
Revises: 
Create Date: 2026-05-02 16:01:21.164170
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '700758466f79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('multiplex', sa.Column('direccion', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('multiplex', 'direccion')
    # ### end Alembic commands ###