"""Alembic migration script template."""
"""init multiplex

Revision ID: 739b049962e4
Revises: 
Create Date: 2026-04-21 10:19:12.490627
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '739b049962e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multiplex',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fechaCreacion', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('sala',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('multiplex_id', sa.String(), nullable=False),
    sa.Column('capacidad_general', sa.Integer(), nullable=True),
    sa.Column('capacidad_preferencial', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['multiplex_id'], ['multiplex.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('silla',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fila', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('sala_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sala_id'], ['sala.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('silla')
    op.drop_table('sala')
    op.drop_table('multiplex')
    # ### end Alembic commands ###