"""Alembic migration script template."""
"""refactor_tablas_facturacion_y_snacks

Revision ID: 8dafc8742529
Revises: 
Create Date: 2026-05-22 09:52:23.465257
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8dafc8742529'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('puntosAcumulados', sa.Integer(), nullable=True),
    sa.Column('fechaRegistro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('estaActivo', sa.Boolean(), nullable=True),
    sa.Column('nombres', sa.String(), nullable=False),
    sa.Column('apellidos', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comidas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion',
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_clave'), 'configuracion', ['clave'], unique=True)
    op.create_index(op.f('ix_configuracion_id'), 'configuracion', ['id'], unique=False)
    op.create_table('multiplex',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('estaActivo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('peliculas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('duracionMinutos', sa.Integer(), nullable=False),
    sa.Column('linkTrailer', sa.String(), nullable=True),
    sa.Column('linkPoster', sa.String(), nullable=True),
    sa.Column('sinopsis', sa.String(), nullable=True),
    sa.Column('estaActiva', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipoSilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigoEmpleado', sa.String(), nullable=False),
    sa.Column('correoLaboral', sa.String(), nullable=False),
    sa.Column('clienteId', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(), nullable=False),
    sa.Column('apellidos', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clienteId'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clienteId'),
    sa.UniqueConstraint('codigoEmpleado'),
    sa.UniqueConstraint('correoLaboral')
    )
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comentario', sa.String(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('pelicula_id', sa.Integer(), nullable=True),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['pelicula_id'], ['peliculas.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clienteId', sa.Integer(), nullable=True),
    sa.Column('subTotal', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('fechaCreacion', sa.DateTime(), nullable=False),
    sa.Column('fechaExpiracionReserva', sa.DateTime(), nullable=True),
    sa.Column('codigoTransaccion', sa.String(length=100), nullable=True),
    sa.Column('estadoFactura', sa.Enum('RESERVADA', 'PAGADA', 'CANCELADA', name='estadofacturaenum'), nullable=False),
    sa.ForeignKeyConstraint(['clienteId'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('salas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('estaActiva', sa.Boolean(), nullable=True),
    sa.Column('capacidadTotal', sa.Integer(), nullable=False),
    sa.Column('capacidadPreferencial', sa.Integer(), nullable=False),
    sa.Column('multiplexId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['multiplexId'], ['multiplex.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero', 'multiplexId', name='uq_sala_numero_multiplex')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empleadoId', sa.Integer(), nullable=False),
    sa.Column('multiplexId', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.Enum('director', 'cajero', 'despachador_comida', 'encargadoSala', 'aseador', 'administrador', name='cargoenum'), nullable=False),
    sa.Column('salario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fechaInicio', sa.Date(), nullable=False),
    sa.Column('fechaFin', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['empleadoId'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['multiplexId'], ['multiplex.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fechaHora', sa.DateTime(), nullable=False),
    sa.Column('fechaHoraFin', sa.DateTime(), nullable=False),
    sa.Column('estaActiva', sa.Boolean(), nullable=False),
    sa.Column('peliculaId', sa.Integer(), nullable=False),
    sa.Column('salaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['peliculaId'], ['peliculas.id'], ),
    sa.ForeignKeyConstraint(['salaId'], ['salas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'EXPIRADO', 'CANCELADO', name='estadopagoenum'), nullable=False),
    sa.Column('metodoPago', sa.String(), nullable=False),
    sa.Column('fechaPago', sa.DateTime(), nullable=True),
    sa.Column('fechaExpiracion', sa.DateTime(), nullable=False),
    sa.Column('facturaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facturaId'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sillas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fila', sa.Integer(), nullable=False),
    sa.Column('columna', sa.Integer(), nullable=False),
    sa.Column('estaActiva', sa.Boolean(), nullable=True),
    sa.Column('salaId', sa.Integer(), nullable=False),
    sa.Column('tipoSillaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['salaId'], ['salas.id'], ),
    sa.ForeignKeyConstraint(['tipoSillaId'], ['tipoSilla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('passwordHash', sa.String(), nullable=False),
    sa.Column('intentosFallidos', sa.Integer(), nullable=True),
    sa.Column('bloqueadoHasta', sa.DateTime(), nullable=True),
    sa.Column('estaActivo', sa.Boolean(), nullable=False),
    sa.Column('rolId', sa.Integer(), nullable=True),
    sa.Column('clienteId', sa.Integer(), nullable=True),
    sa.Column('empleadoId', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clienteId'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empleadoId'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['rolId'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clienteId'),
    sa.UniqueConstraint('empleadoId')
    )
    op.create_table('boletas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('funcionId', sa.Integer(), nullable=False),
    sa.Column('sillaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcionId'], ['funciones.id'], ),
    sa.ForeignKeyConstraint(['sillaId'], ['sillas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionId', 'sillaId', name='uq_boleta_funcion_silla')
    )
    op.create_table('historial_cargos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empleadoId', sa.Integer(), nullable=False),
    sa.Column('cargoAnterior', sa.Enum('director', 'cajero', 'despachador_comida', 'encargadoSala', 'aseador', 'administrador', name='cargoenum'), nullable=True),
    sa.Column('cargoNuevo', sa.Enum('director', 'cajero', 'despachador_comida', 'encargadoSala', 'aseador', 'administrador', name='cargoenum'), nullable=False),
    sa.Column('multiplexId', sa.Integer(), nullable=True),
    sa.Column('fechaCambio', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('registradoPorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empleadoId'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['multiplexId'], ['multiplex.id'], ),
    sa.ForeignKeyConstraint(['registradoPorId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refreshtoken',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('tokenHash', sa.String(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuarioId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_facturas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precioUnitario', sa.Float(), nullable=False),
    sa.Column('subTotal', sa.Float(), nullable=False),
    sa.Column('facturaId', sa.Integer(), nullable=False),
    sa.Column('boletaId', sa.Integer(), nullable=True),
    sa.Column('comidaId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boletaId'], ['boletas.id'], ),
    sa.ForeignKeyConstraint(['comidaId'], ['comidas.id'], ),
    sa.ForeignKeyConstraint(['facturaId'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_facturas')
    op.drop_table('refreshtoken')
    op.drop_table('historial_cargos')
    op.drop_table('boletas')
    op.drop_table('usuarios')
    op.drop_table('sillas')
    op.drop_table('pagos')
    op.drop_table('funciones')
    op.drop_table('contratos')
    op.drop_table('salas')
    op.drop_table('rol_permiso')
    op.drop_table('facturas')
    op.drop_table('evaluaciones')
    op.drop_table('empleados')
    op.drop_table('tipoSilla')
    op.drop_table('servicios')
    op.drop_table('rol')
    op.drop_table('permiso')
    op.drop_table('peliculas')
    op.drop_table('multiplex')
    op.drop_index(op.f('ix_configuracion_id'), table_name='configuracion')
    op.drop_index(op.f('ix_configuracion_clave'), table_name='configuracion')
    op.drop_table('configuracion')
    op.drop_table('comidas')
    op.drop_table('clientes')
    # ### end Alembic commands ###