"""Alembic migration script template."""
"""create multiplex cartelera table

Revision ID: 8f315aacea62
Revises: d9bfc3faad01
Create Date: 2026-05-23 08:57:30.615426
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8f315aacea62'
down_revision = 'd9bfc3faad01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multiplex_cartelera',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('multiplexId', sa.Integer(), nullable=False),
    sa.Column('peliculaId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['multiplexId'], ['multiplex.id'], ),
    sa.ForeignKeyConstraint(['peliculaId'], ['peliculas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('multiplexId', 'peliculaId', name='uq_multiplex_pelicula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multiplex_cartelera')
    # ### end Alembic commands ###