"""Alembic migration script template."""
"""remove unique constraint from sala.numero

Revision ID: a20362100baf
Revises: 700758466f79
Create Date: 2026-05-04 07:15:51.673274
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a20362100baf'
down_revision = '700758466f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('salas_numero_key'), 'salas', type_='unique')
    op.create_unique_constraint('uq_sala_numero_multiplex', 'salas', ['numero', 'multiplexId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sala_numero_multiplex', 'salas', type_='unique')
    op.create_unique_constraint(op.f('salas_numero_key'), 'salas', ['numero'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###