"""Alembic migration script template."""
"""Add seq to empleado

Revision ID: ae9491781158
Revises: 62d1636e4e5d
Create Date: 2026-05-05 02:41:51.724117
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ae9491781158'
down_revision = '62d1636e4e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('seq', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleados', 'seq')
    # ### end Alembic commands ###