"""Alembic migration script template."""
"""Crear tabla cliente

Revision ID: cc50ff18e0fe
Revises: a20362100baf
Create Date: 2026-05-05 00:36:25.435083
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cc50ff18e0fe'
down_revision = 'a20362100baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('nombre_completo', sa.String(), nullable=False))
    op.add_column('clientes', sa.Column('correo', sa.String(), nullable=False))
    op.add_column('clientes', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('clientes', sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('clientes', sa.Column('activo', sa.Boolean(), nullable=True))
    op.add_column('clientes', sa.Column('puntos_acumulados', sa.Integer(), nullable=True))
    op.add_column('clientes', sa.Column('idioma_preferido', sa.String(), nullable=True))
    op.create_index(op.f('ix_clientes_correo'), 'clientes', ['correo'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.drop_constraint(op.f('clientes_id_fkey'), 'clientes', type_='foreignkey')
    op.drop_column('clientes', 'puntaje')
    op.drop_constraint(op.f('salas_numero_key'), 'salas', type_='unique')
    op.create_unique_constraint('uq_sala_numero_multiplex', 'salas', ['numero', 'multiplexId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sala_numero_multiplex', 'salas', type_='unique')
    op.create_unique_constraint(op.f('salas_numero_key'), 'salas', ['numero'], postgresql_nulls_not_distinct=False)
    op.add_column('clientes', sa.Column('puntaje', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('clientes_id_fkey'), 'clientes', 'personas', ['id'], ['id'])
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_correo'), table_name='clientes')
    op.drop_column('clientes', 'idioma_preferido')
    op.drop_column('clientes', 'puntos_acumulados')
    op.drop_column('clientes', 'activo')
    op.drop_column('clientes', 'fecha_registro')
    op.drop_column('clientes', 'password_hash')
    op.drop_column('clientes', 'correo')
    op.drop_column('clientes', 'nombre_completo')
    # ### end Alembic commands ###