"""Alembic migration script template."""
"""add unique constraint to pelicula titulo

Revision ID: d9bfc3faad01
Revises: 8dafc8742529
Create Date: 2026-05-23 08:52:46.389022
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd9bfc3faad01'
down_revision = '8dafc8742529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multiplex_cartelera')
    op.create_unique_constraint(None, 'peliculas', ['titulo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'peliculas', type_='unique')
    op.create_table('multiplex_cartelera',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('multiplexId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('peliculaId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['multiplexId'], ['multiplex.id'], name=op.f('multiplex_cartelera_multiplexId_fkey')),
    sa.ForeignKeyConstraint(['peliculaId'], ['peliculas.id'], name=op.f('multiplex_cartelera_peliculaId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('multiplex_cartelera_pkey')),
    sa.UniqueConstraint('multiplexId', 'peliculaId', name=op.f('uq_multiplex_pelicula'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###