"""Alembic migration script template."""
"""add seccion peliculas y cartelera

Revision ID: ddcb0be35395
Revises: 7f18848488b1
Create Date: 2026-05-21 08:37:15.384314
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ddcb0be35395'
down_revision = '7f18848488b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multiplex_cartelera')
    op.add_column('funciones', sa.Column('fechaHoraFin', sa.DateTime(), nullable=False))
    op.add_column('peliculas', sa.Column('estaActiva', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peliculas', 'estaActiva')
    op.drop_column('funciones', 'fechaHoraFin')
    op.create_table('multiplex_cartelera',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('multiplexId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('peliculaId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['multiplexId'], ['multiplex.id'], name=op.f('multiplex_cartelera_multiplexId_fkey')),
    sa.ForeignKeyConstraint(['peliculaId'], ['peliculas.id'], name=op.f('multiplex_cartelera_peliculaId_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('multiplex_cartelera_pkey')),
    sa.UniqueConstraint('multiplexId', 'peliculaId', name=op.f('uq_multiplex_pelicula'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###