"""Alembic migration script template."""
"""Crear tabla cliente final

Revision ID: ddf41aba2d53
Revises: a20362100baf
Create Date: 2026-05-05 01:20:56.754493
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ddf41aba2d53'
down_revision = 'a20362100baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Primero eliminamos las FK que dependen de clientes
    op.drop_constraint('evaluaciones_cliente_id_fkey', 'evaluaciones', type_='foreignkey')
    op.drop_constraint('facturas_clienteId_fkey', 'facturas', type_='foreignkey')
    
    op.drop_table('clientes')
    op.create_table('clientes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre_completo', sa.String(), nullable=False),
        sa.Column('correo', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('activo', sa.Boolean(), nullable=True),
        sa.Column('puntos_acumulados', sa.Integer(), nullable=True),
        sa.Column('idioma_preferido', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_correo'), 'clientes', ['correo'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    
    # Recreamos las FK
    op.create_foreign_key('evaluaciones_cliente_id_fkey', 'evaluaciones', 'clientes', ['cliente_id'], ['id'])
    op.create_foreign_key('facturas_clienteId_fkey', 'facturas', 'clientes', ['clienteId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sala_numero_multiplex', 'salas', type_='unique')
    op.create_unique_constraint(op.f('salas_numero_key'), 'salas', ['numero'], postgresql_nulls_not_distinct=False)
    op.add_column('clientes', sa.Column('puntaje', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('clientes_id_fkey'), 'clientes', 'personas', ['id'], ['id'])
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_correo'), table_name='clientes')
    op.drop_column('clientes', 'idioma_preferido')
    op.drop_column('clientes', 'puntos_acumulados')
    op.drop_column('clientes', 'activo')
    op.drop_column('clientes', 'fecha_registro')
    op.drop_column('clientes', 'password_hash')
    op.drop_column('clientes', 'correo')
    op.drop_column('clientes', 'nombre_completo')
    # ### end Alembic commands ###