"""Alembic migration script template."""
"""remove unique constraint boleta

Revision ID: ea7b6c2bfdfd
Revises: 11629e0d629c
Create Date: 2026-05-24 18:47:13.517458
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ea7b6c2bfdfd'
down_revision = '11629e0d629c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###