"""Alembic migration script template."""
"""empleado cliente relation

Revision ID: eff3ecd968ec
Revises: 06a12b5e44ef
Create Date: 2026-05-17 17:44:42.039020
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'eff3ecd968ec'
down_revision = '06a12b5e44ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('clienteId', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'empleados', ['clienteId'])
    op.create_foreign_key(None, 'empleados', 'clientes', ['clienteId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empleados', type_='foreignkey')
    op.drop_constraint(None, 'empleados', type_='unique')
    op.drop_column('empleados', 'clienteId')
    # ### end Alembic commands ###