"""Alembic migration script template."""
"""Actualizar Empleado y agregar HistorialCargo

Revision ID: fa5a32602dd1
Revises: 458894e040b9
Create Date: 2026-05-05 02:14:05.530225
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fa5a32602dd1'
down_revision = '458894e040b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('cedula', sa.String(), nullable=False))
    op.add_column('empleados', sa.Column('nombre_completo', sa.String(), nullable=False))
    op.add_column('empleados', sa.Column('fecha_inicio_contrato', sa.Date(), nullable=False))
    op.add_column('empleados', sa.Column('salario', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('empleados', sa.Column('activo', sa.Boolean(), nullable=True))
    op.add_column('empleados', sa.Column('multiplex_id', sa.Integer(), nullable=True))
    op.add_column('empleados', sa.Column('correo_laboral', sa.String(), nullable=True))
    op.drop_constraint(op.f('empleados_codigoEmpleado_key'), 'empleados', type_='unique')
    op.drop_constraint(op.f('empleados_correoEmpleado_key'), 'empleados', type_='unique')
    op.create_unique_constraint(None, 'empleados', ['correo_laboral'])
    op.create_unique_constraint(None, 'empleados', ['cedula'])
    op.create_foreign_key(None, 'empleados', 'multiplex', ['multiplex_id'], ['id'])
    op.drop_column('empleados', 'correoEmpleado')
    op.drop_column('empleados', 'codigoEmpleado')
    op.drop_column('empleados', 'fechaIngreso')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('fechaIngreso', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('empleados', sa.Column('codigoEmpleado', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('empleados', sa.Column('correoEmpleado', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'empleados', type_='foreignkey')
    op.drop_constraint(None, 'empleados', type_='unique')
    op.drop_constraint(None, 'empleados', type_='unique')
    op.create_unique_constraint(op.f('empleados_correoEmpleado_key'), 'empleados', ['correoEmpleado'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('empleados_codigoEmpleado_key'), 'empleados', ['codigoEmpleado'], postgresql_nulls_not_distinct=False)
    op.drop_column('empleados', 'correo_laboral')
    op.drop_column('empleados', 'multiplex_id')
    op.drop_column('empleados', 'activo')
    op.drop_column('empleados', 'salario')
    op.drop_column('empleados', 'fecha_inicio_contrato')
    op.drop_column('empleados', 'nombre_completo')
    op.drop_column('empleados', 'cedula')
    # ### end Alembic commands ###